{
    # image encoder settings
    encoder_name: 'openclip-H',
    adapter_config: {"mlp": {"adapter_type": "normal", "downsample_factor": 8}, "attention": {"adapter_type": "normal", "downsample_factor": 8}},
    freeze_img_encoder: false,

    # language model settings
    lm_name: "neox",
    lm_path: "EleutherAI/pythia-19m",

    # train settings
    micro_batch_size: 2,
    gradient_accumulation_steps: 1,
    workers: 4,
    bench_warmup: 10,
    bench_steps: 100,
    lr: 8.0e-4,
    min_lr: 0.0,
    lr_decay_iters: 300000,
    image_enc_lr: 2.0e-6,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.1,

    zero_stage: 2,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    # dataset_type: 'new',


    save: "/gpfs/alpine/scratch/lfsm/csc499/checkpoints/MAGMA_19M_clipH",
    load: "/gpfs/alpine/scratch/lfsm/csc499/checkpoints/MAGMA_19M_clipH",

    eval_every: 250,
    wandb_project: "MAGMA_19M_clipH",
    name: "MAGMA_19M_clipH"
}
