{
    # image encoder settings
    encoder_name: 'openclip-H',
    adapter_config: {"mlp": {"adapter_type": "normal", "downsample_factor": 8}, "attention": {"adapter_type": "normal", "downsample_factor": 8}},
    freeze_img_encoder: false,

    # language model settings
    lm_name: "neox",
    lm_path: "EleutherAI/pythia-19m",

    # train settings
    batch_size: 6,
    train_steps: 10,
    lr: 8.0e-4,
    min_lr: 0.0,
    lr_decay_iters: 300000,
    image_enc_lr: 2.0e-6,
    use_image_embed_layernorm: true,
    image_embed_dropout_prob: 0.1,
    image_size: 384,

    gradient_accumulation_steps: 1,
    zero_stage: 2,
    gradient_clipping: 1.0,

    # dataset / save / load settings
    # dataset_type: 'new',
    train_dataset_dir: ['/gpfs/alpine/csc499/proj-shared/magma/flickr8k_processed'], #'/mnt/brick/wit_converted'

    eval_dataset_dir: null, # if this is none, train dataset will be split
    # vqa_dir: "/mnt/localdisk/vqa_val_converted",
    # gqa_dir: "/mnt/localdisk/gqa_val_converted",

    save: "checkpoints/MAGMA_19M_clipH",
    load: "checkpoints/MAGMA_19M_clipH",

    eval_every: 250,
    wandb_project: "MAGMA_19M_clipH",
    name: "MAGMA_19M_clipH"
}
